# Generated by Django 4.2.9 on 2024-10-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='viewd',
        ),
    ]
