# Generated by Django 4.2.9 on 2024-10-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMidiaUse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('use_of_social_midia', models.IntegerField(choices=[(0, 'Menos de Uma Hora por Dia'), (1, 'Uma a Tres Horas por Dia'), (2, 'Tres a Cinco Horas por Dia'), (3, 'Mais de Cinco Horas por Dia')], verbose_name='Tempo em Midias Sociais')),
                ('social_media_comparison', models.IntegerField(choices=[(0, 'Sinto inspirado e fico feliz pelo sucesso dos outros'), (1, 'Normalmente me sinto indiferente e apenas observo'), (2, 'As vezes me sinto incomodado, mas tento não me comparar'), (3, 'Frequentemente me comparo me sinto inferior')], verbose_name='Comparação em Midias Sociais')),
                ('selfknowledge_about_social_media_use', models.IntegerField(choices=[(0, 'Não sinto que passo tempo demais nas redes'), (1, 'As vezes me preocupo com isso'), (2, 'Frequentemente, mas tento controlar'), (3, 'Sempre sinto que estou passando muito tempo online')], verbose_name='Autoconhecimento sobre uso de social midia')),
                ('check_social_networks_when_offline', models.IntegerField(choices=[(0, 'Não sinto vontade de checar as redes sociais quando estou offiline'), (1, 'Raramente penso em checar quando estou offiline'), (2, 'As vezes me sinto vontade de checar, mas consigo me controlar'), (3, 'Sim, sinto uma necessidade constante de verificar')], verbose_name='Checar redes sociais quando offline')),
                ('would_prefer_to_use_less_social_media', models.IntegerField(choices=[(0, 'Não, estou satisfeito com o tempo que passo nas redes'), (1, 'Talvez, mas não sei se conseguiria'), (2, 'Sim, mas ainda não tomei nenhuma ação'), (3, 'Sim, definitivamente, mas tenho dificuldade em reduzir')], verbose_name='Preferiria usar menos midias sociais')),
                ('result', models.IntegerField(choices=[(0, 'Usa muito pouco'), (1, 'Uso moderado'), (2, 'Usa muito'), (3, 'Preocupante')], verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Uso de Midias Sociais',
                'verbose_name_plural': 'Uso de Midias Sociais',
                'ordering': ['-created_at'],
            },
        ),
    ]
