# Generated by Django 4.2.9 on 2024-10-01 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_is_client_remove_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModels',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=120, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
