name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  NAME_LOCAL: ${{ vars.NAME_LOCAL }}
  PORT_LOCAL: ${{ vars.PORT_LOCAL }}
  USER_LOCAL: ${{ vars.USER_LOCAL }}
  HOST_LOCAL: ${{ vars.HOST_LOCAL }}
  PASSWORD_LOCAL: ${{ vars.PASSWORD_LOCAL }}
  EMAIL_PORT: ${{ vars.EMAIL_PORT }}
  EMAIL_HOST: ${{ vars.EMAIL_HOST }}
  EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ vars.EMAIL_HOST_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
