name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  NAME_LOCAL: ${{ secrets.NAME_LOCAL }}
  PORT_LOCAL: ${{ secrets.PORT_LOCAL }}
  USER_LOCAL: ${{ secrets.USER_LOCAL }}
  HOST_LOCAL: ${{ secrets.HOST_LOCAL }}
  PASSWORD_LOCAL: ${{ secrets.PASSWORD_LOCAL }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DATABASE: |
          default:
            ENGINE: django.db.backends.postgresql
            NAME: ${{ env.NAME_LOCAL }}
            USER: ${{ env.USER_LOCAL }}
            PASSWORD: ${{ env.PASSWORD_LOCAL }}
            HOST: ${{ env.HOST_LOCAL }}
            PORT: ${{ env.PORT_LOCAL }}
